apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorites-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favorites-service
  template:
    metadata:
      labels:
        app: favorites-service
    spec:
      containers:
        - name: favorites-service
          image: favorites-service:1.0
          imagePullPolicy: Never
          #image: sagariprashanth/favorites-service:1.0
          #imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/favorite_db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
